Albino Dino sprite/animation names
pmret/papermario pull request #1042
Opened 2023-04-30 10:26 UTC by Ponmander

2023-04-30 19:18 UTC, HailSanta commented on tools/splat_ext/npc.yaml
> +    - BurntDead
These two are usually BurnHurt and BurnStill

2023-04-30 19:18 UTC, HailSanta commented on tools/splat_ext/npc.yaml
> +    - FwdTalk
Suffix with Fwd/Back like you did for Still

2023-04-30 19:18 UTC, HailSanta commented on tools/splat_ext/npc.yaml
> +    - Pain
There are usually Hurt/HurtStill

2023-04-30 19:54 UTC, ethteck requested changes
Jenkins is failing because the rom doesn't match anymore. I commented where the issue starts, I believe, but I think there are 2 or more mistakes. You can verify it's fixed yourself by running `ninja` and making sure you get a matching build.

2023-04-30 19:54 UTC, ethteck commented on src/battle/area/pra/actor/albino_dino.c
> +            EVT_SET_CONST(LVar1, ANIM_AlbinoDino_Dead)
Some changes around here are wrong. 8 is pain, but you changed 8 to dead here. also the build doesn't match (jenkins failed, and your local build should be failing too) - please fix these

2023-04-30 20:09 UTC, nanaian commented
You can use `vbindiffvbindiff ver/us/baserom.z64 ver/us/build/papermario.z64` to view the differences:
<img width="485" alt="image" src="https://user-images.githubusercontent.com/9429556/235374071-088be754-9200-4c8d-8071-eb3893fd848f.png">

2023-05-01 09:22 UTC, Ponmander commented
I need to get back to this. I am hoping I just mixed up the animation IDs for things.

2023-05-01 19:55 UTC, merged