Document PRNG Related Functions
pmret/papermario pull request #1060
Opened 2023-05-20 22:42 UTC by Lincoln-LM

This is a pretty simple PR that gives some functions and constants more fitting names, restructures the ``gfx_rand_int`` (formerly ``func_E0200000``) and ``advance_rng`` functions to match their intended implementations, and adds a few comments explaining them.

2023-05-20 23:07 UTC, pixel-stuck commented on include/effects_internal.h
> +s32 gfx_rand_int(s32);
Not quite sure I'd call this "gfx" as that's often what we use to refer to things that are directly interfacing with the n64 graphics hardware. Its a silly differentiation, but these graphical effects are just referred to as "fx" or "effect" I think "effect_rand_int" is probably a good name.

2023-05-21 02:18 UTC, HailSanta requested changes

2023-05-21 02:18 UTC, HailSanta commented on src/43F0.c
> +    u32 partition_size = 0xFFFFFFFF;
partitionSize and maxPlusOne case for local cariables

2023-05-21 13:52 UTC, ethteck approved these changes
Thanks for the cool PR! :)

2023-05-22 14:37 UTC, merged