Implemented kkj_19_5_baking_GetItemNameRaw for pal
pmret/papermario pull request #1066
Opened 2023-06-17 15:18 UTC by Keksnet

In this PR I implemented the GetItemNameRaw for kkj_19_5_baking.c

2023-06-17 15:26 UTC, BowserSlug commented
🚀 This PR matches 1 function (+0.00%) on `pal`.

2023-06-18 20:34 UTC, Keksnet commented
Merged two PR with additional functions into this one.
https://github.com/pmret/papermario/pull/1068 and https://github.com/pmret/papermario/pull/1067 are now obsolete.

2023-06-18 21:00 UTC, ethteck requested changes
Thanks for your work! A few style suggestions, but otherwise this looks great!

2023-06-19 23:35 UTC, ethteck requested changes
Thanks, just a couple more things!

2023-06-19 23:35 UTC, ethteck commented on src/world/area_mgm/mgm_01/mgm_01_2_npc.c
> +    Enemy * scorekeeper = get_enemy(SCOREKEEPER_ENEMY_IDX);
```suggestion
    Enemy* scorekeeper = get_enemy(SCOREKEEPER_ENEMY_IDX);
```

2023-06-19 23:35 UTC, ethteck commented on src/world/area_kkj/kkj_19/kkj_19_5_baking.c
> +    ITEM_BAKING_FLOUR,      MSG_Menus_BakingFlour,
each of these lines needs an open / close paren around it (see the warning mentioned in the bowser slug comment)

2023-06-20 01:51 UTC, HailSanta requested changes

2023-06-20 01:51 UTC, HailSanta commented on src/world/area_mgm/mgm_01/mgm_01_2_npc.c
> +    evt_set_variable(script, LocalVar(13), remaining);
This should be written LVarD

2023-06-20 01:51 UTC, HailSanta commented on src/world/area_mgm/mgm_02/mgm_02_0_header.c
> +        msgID = 0;
use MSG_NONE instead of 0 here

2023-06-20 01:51 UTC, HailSanta commented on src/world/area_kkj/kkj_19/kkj_19_5_baking.c
> +    for (i = 0; i < ARRAY_COUNT(kkj_19_BakingIngredientsNames); i++) {
Use namespace macro N(BakingIngredientsNames)
Likewise for other occurrences

2023-06-20 06:57 UTC, marijnvdwerf requested changes

2023-06-20 06:57 UTC, marijnvdwerf commented on src/world/area_kkj/kkj_19/kkj_19_5_baking.c
> +};
All structs in the codebase are declared using a typedef, and none of them are namespaced.

```suggestion
typedef struct BakingIngredient {
    s32 itemID;
    s32 nameID;
} BakingIngredient;
```

2023-06-20 06:57 UTC, marijnvdwerf commented on src/world/area_mgm/mgm_01/mgm_01_2_npc.c
> +}
This entire function can be combined with the non-PAL version;

```c
#if VERSION_PAL
    evt_set_variable(script, LocalVar(13), remaining);
#else
    set_message_msg((remaining == 1) ? (s32)&MessageSingular : (s32)&MessagePlural, 1);
#endif
```

2023-06-20 20:47 UTC, marijnvdwerf commented on src/world/area_mgm/mgm_02/mgm_02_0_header.c
> +extern s32 mgm_02_pal_variable;
This can probably be defined/used using `N(pal_variable)`, and the declaration can be moved to a header.

2023-06-22 00:44 UTC, merged