more pal funcs & npc sprites improvement
pmret/papermario pull request #1079
Opened 2023-07-06 11:51 UTC by ethteck

Changes to npc sprites should be more stable now

2023-07-06 11:59 UTC, BowserSlug commented
🚀🚀🚀🚀🚀🚀 This PR matches 6 functions (+0.08%) on `pal`.

2023-07-09 22:16 UTC, nanaian requested changes

2023-07-09 22:16 UTC, nanaian commented on include/enums.h
> +# if VERSION_PAL
```suggestion
#if VERSION_PAL
```

2023-07-10 05:54 UTC, HailSanta commented on include/enums.h
> +    UNK3,
FILE_MESSAGE_BASE_UNK

2023-07-10 05:57 UTC, merged