Name many funcs to match upcoming Star Rod 0.4.0 release
pmret/papermario pull request #170
Opened 2021-02-06 15:21 UTC by nanaian

2021-02-06 17:57 UTC, ethteck approved these changes

2021-02-08 16:25 UTC, ethteck approved these changes

2021-02-08 19:28 UTC, pixel-stuck requested changes

2021-02-08 19:28 UTC, pixel-stuck commented on src/func_801489B8.s
>  .set noat      # allow manual use of $at
what's up with moving this file?

2021-02-08 19:32 UTC, nanaian commented on src/func_801489B8.s
>  .set noat      # allow manual use of $at
whoops, will fix

2021-02-09 03:33 UTC, merged