Splat update
pmret/papermario pull request #173
Opened 2021-02-08 18:23 UTC by ethteck

Depends on #169 

Splat update, lots of libultra cleanup and some decomp, some data migration, and other odds and ends.

2021-02-08 18:26 UTC, ethteck commented
I forgot, this also includes the last of the obvious file splits. Pretty much all the remaining splits were in libultra. A couple functions have been converted back to hasm since I confirmed they're not compiled, which reduces the max number of functions in progress.py.

2021-02-08 19:06 UTC, nanaian approved these changes

2021-02-08 19:06 UTC, nanaian commented on .vscode/settings.json
> +        "ranges": "c"
sigh

2021-02-08 19:39 UTC, pixel-stuck requested changes

2021-02-08 19:39 UTC, pixel-stuck commented on include/functions.h
> +//s32 rand_int(s32);
?

2021-02-09 01:46 UTC, nanaian approved these changes

2021-02-09 01:48 UTC, merged