Partner-related things
pmret/papermario pull request #176
Opened 2021-02-09 16:52 UTC by nanaian

2021-02-09 17:02 UTC, ethteck commented on include/variables.h
> +PlayerStatus* gPlayerStatusPtr;
whuh

2021-02-09 17:08 UTC, ethteck commented on src/world/partners.c
> +INCLUDE_ASM(s32, "code_838b0_len_5900", use_consumable);
code_838b0_len_5900 these refs should be renamed and the asm moved

2021-02-09 17:17 UTC, ethteck submitted a review, later dismissed

2021-02-10 06:04 UTC, pixel-stuck requested changes

2021-02-10 06:04 UTC, pixel-stuck commented on src/world/actions.c
> +s32 D_800F7C7C[] = { 0x800F7BE8, 0x800F7BE8, 0x800F7BBC, 0x800F7B94 };
pointers here.

2021-02-10 06:04 UTC, pixel-stuck commented on src/world/actions.c
> +s32 D_800F7B50[] = { 0x417C1B33, 0xC0EC5C14, 0x405C9AAA, 0xBF400000 };
these look like floats

2021-02-10 06:04 UTC, pixel-stuck commented on src/world/actions.c
> +s32 D_800F7B60[] = { 0x3E1E0C17, 0xBEB33DB0, 0xBE3AA2E4, 0x3C3CBE62 };
potentially also floats... not 100% sure tho

2021-02-10 06:04 UTC, pixel-stuck commented on src/world/actions.c
> +s32 D_800F7B70[] = { 0x40000000, 0x40800000, 0x42000000, 0xC2000000 };
more potential floats

2021-02-10 06:04 UTC, pixel-stuck commented on src/world/partner/goombario.c
> +void world_goombario_pre_battle(Npc* partner) {
arg0 isn't renamed in the body of the func.

2021-02-10 06:04 UTC, pixel-stuck commented on src/world/partners.c
> +    0x80107CA8, 0x80107CF8, 0x80107D48, 0x80107D98, 0x80107DE8, 0x80107CA8, 0x80107E88, 0x80107ED8, 0x80107F28, 0x80107E38, 0x80107FC8, 0x80107FC8, 0x80107FC8, 0x80107FC8, 0x80107FC8, 0x80107FC8,
pointers, here and below

2021-02-10 06:04 UTC, pixel-stuck commented on src/world/partners.c
> +s32 D_800F8010[] = { 0x003251D0, 0x00325AD0, 0x802C05CC, 0x00000000 };
pointer

2021-02-10 15:49 UTC, merged