Battle items
pmret/papermario pull request #222
Opened 2021-03-23 18:26 UTC by Kelebek1

2021-03-23 21:43 UTC, nanaian requested changes
Whew, this is a big PR - thank you for it! ✨ 

Just one small nit in each item's main script - `SI_VAR(10)` holds that item's ID, and preferably we'd use the enum name (e.g. `ItemID_Coconut`) there rather than a magic number.

(In the future it would be good to throw the duplicated code into an `.inc.c` file and include it from each item instead, but there's no need to do that in this PR :shipit:)

2021-03-23 21:43 UTC, nanaian commented on src/battle/item/dizzy_dial/dizzy_dial.c
> +    SI_VAR(10) = c 0x9A;
This should be `= c ItemID_DizzyDial` I'm pretty sure.
Same for other items - obviously different item IDs, but they should exist in `enums.h`.

2021-03-23 21:47 UTC, nanaian commented
Looks like [https://github.com/pmret/papermario/pull/222/commits/daeaa6ce41d4e275c800206f504cf2f32c8f803c](daeaa6c "Volt Shroom") included running `format.sh`. It still says in CONTRBUTING.md to do this, but we've stopped doing it recently because of some inconsistencies between `astyle` versions. The changes it did make look fine, though, although it might be worth rebasing/force-pushing away changes outside of `src/battle/item/`. cc @ethteck

2021-03-23 22:40 UTC, Kelebek1 commented
> 
> 
> Looks like [daeaa6c "Volt Shroom"](https://github.com/pmret/papermario/pull/222/commits/daeaa6ce41d4e275c800206f504cf2f32c8f803c) included running `format.sh`. It still says in CONTRBUTING.md to do this, but we've stopped doing it recently because of some inconsistencies between `astyle` versions. The changes it did make look fine, though, although it _might_ be worth rebasing/force-pushing away changes outside of `src/battle/item/`... cc @ethteck for opinion

How do I do that? I'm not good enough with git to figure out how to do it.

2021-03-23 22:51 UTC, nanaian commented
Don't worry about doing it for now, we'll see what @ethteck says

2021-03-23 23:14 UTC, Kelebek1 commented
Is there a list anywhere of possible variables? Like I see "$damage"  for example, how/where is that defined?

2021-03-24 02:03 UTC, ethteck commented on src/battle/item/dried_shroom/lib.c
> +            PlaySoundAtActor(ActorID_PLAYER, 8341);
We probably want the second argument to instances of PlaySoundAtActor to be in hex, assuming it's a sound ID, and we might even have the define for it

2021-03-24 02:12 UTC, ethteck commented
I'm cool with the formatting changes. After all, they are what we want basically. Overall I'm fine with this PR as-is, and I'll inc.c the duplicate funcs later on. Amazing work.

2021-03-24 02:26 UTC, ethteck approved these changes

2021-03-24 07:41 UTC, nanaian commented
> Is there a list anywhere of possible variables? Like I see "$damage"  for example, how/where is that defined?

These are just compiled into SI_VAR(0), SI_VAR(1), etc sequentially.
See the GitHub wiki page on the script DSL for more info.

2021-03-24 07:41 UTC, nanaian approved these changes

2021-03-24 08:39 UTC, merged