Disassemble Some Icons
pmret/papermario pull request #242
Opened 2021-03-29 08:24 UTC by JoshDuMan

2021-03-29 08:25 UTC, JoshDuMan commented
Still working for a bit tonight, just wanted to open for some feedback now.

2021-03-30 10:02 UTC, nanaian requested changes
Could you make the folder names singular (i.e. `upgrade/super_boots`, not `upgrades/super_boots`) and put _all_ of these under an `icon/` directory?

2021-03-30 11:04 UTC, nanaian commented on ver/us/splat.yaml
> +  - [0x1CC310, ci4,     test/present , 32, 32]
random space before comma

2021-03-31 12:29 UTC, nanaian approved these changes

2021-03-31 12:29 UTC, merged