match funcs in code_a5dd0_len_114e0
pmret/papermario pull request #249
Opened 2021-04-01 18:58 UTC by Rainchus

2021-04-01 19:04 UTC, nanaian requested changes

2021-04-01 19:04 UTC, nanaian commented on src/code_a5dd0_len_114e0.c
> +    entity = get_entity_by_index(entityIndex);
merge this with line 126

2021-04-01 19:04 UTC, nanaian commented on src/code_a5dd0_len_114e0.c
> +//INCLUDE_ASM(s32, "code_a5dd0_len_114e0", func_8011085C);
remove comment

2021-04-01 19:04 UTC, nanaian commented on src/code_a5dd0_len_114e0.c
> +    shadow = get_shadow_by_index(entityIndex);
merge with line 182

2021-04-01 19:04 UTC, nanaian commented on src/code_a5dd0_len_114e0.c
> +    s32 temp_v0;
remove these two

2021-04-01 19:46 UTC, nanaian approved these changes

2021-04-02 05:50 UTC, ethteck commented
gg!

2021-04-02 05:50 UTC, merged