area_dgb
pmret/papermario pull request #254
Opened 2021-04-07 18:05 UTC by Kelebek1

Beep beep, big commit coming through.

2021-04-07 18:49 UTC, nanaian commented on ver/us/splat.yaml
> +    - [0xC59820, .rodata, C55F40]
Why indent these like this?

2021-04-07 18:58 UTC, Kelebek1 commented on ver/us/splat.yaml
> +    - [0xC59820, .rodata, C55F40]
Just so they line up. No real reason.

2021-04-08 10:37 UTC, ethteck approved these changes
Other than the newline thing, lgtm!

2021-04-08 10:37 UTC, ethteck commented on src/code_EB8E90.c
> +INCLUDE_ASM(s32, "code_EB8E90", func_80240EFC_EB9D4C);
newlines at end of files please

2021-04-08 16:51 UTC, nanaian requested changes
Can you move `new_lines.py` into `tools`?

2021-04-08 17:23 UTC, Kelebek1 commented
> 
> 
> Can you move `new_lines.py` into `tools`?

I put it with format.sh since it's meant to do the same sort of thing, just format files, but I'll move it.

2021-04-08 17:42 UTC, merged