decompiles most functions in code_b72b0_len_15ed0.c
pmret/papermario pull request #256
Opened 2021-04-12 06:06 UTC by pixel-stuck

2021-04-12 07:23 UTC, ethteck requested changes
Nice! mostly just anding stuff together and hex to dec, but other than that, lgtm!

2021-04-12 07:23 UTC, ethteck commented on src/code_b72b0_len_15ed0.c
> +    newEntityModel->renderMode = (u8)1;
this cast should be unnecessary

2021-04-12 07:23 UTC, ethteck commented on src/code_b72b0_len_15ed0.c
> +        if (entityModel != NULL) {
I think these conditions should be anded together

2021-04-12 07:23 UTC, ethteck commented on src/code_b72b0_len_15ed0.c
> +    if (entityModel != NULL) {
these can be anded

2021-04-12 07:23 UTC, ethteck commented on src/code_b72b0_len_15ed0.c
> +    if (entityModel != NULL) {
these too

2021-04-12 07:23 UTC, ethteck commented on src/code_b72b0_len_15ed0.c
> +        if (entity != NULL) {
these can be anded too

2021-04-12 07:23 UTC, ethteck commented on src/code_b72b0_len_15ed0.c
> +        if (entity != NULL) {
here2

2021-04-12 07:23 UTC, ethteck commented on src/code_b72b0_len_15ed0.c
> +        if (entity != NULL) {
here3

2021-04-12 07:23 UTC, ethteck commented on src/code_b72b0_len_15ed0.c
> +    D_8015437C = 0xA;
We've been using decimal for non-flag values, so I think all these numbres here and in init_entity_models should be changed

2021-04-12 07:53 UTC, ethteck approved these changes

2021-04-12 09:56 UTC, nanaian requested changes

2021-04-12 09:56 UTC, nanaian commented on src/code_b72b0_len_15ed0.c
> +        if ((entity != NULL) && !(entity->flags & 2)) {
Can you remove the parens around `(entity != NULL)` here and the below function? I'd rather not have extraneous parentheses

2021-04-13 00:06 UTC, nanaian approved these changes

2021-04-13 00:07 UTC, merged