Decompilation of duplicated functions
pmret/papermario pull request #354
Opened 2021-08-03 12:27 UTC by Brotenko

2021-08-03 12:34 UTC, ethteck requested changes
aside from that one thing, looks good. Awesome!!!

2021-08-03 12:34 UTC, ethteck commented on src/world/common/UnkNpcAIFunc30.inc.c
> +    npc->duration -= 1;
we do -- for -= 1

2021-08-03 12:46 UTC, ethteck approved these changes

2021-08-04 08:45 UTC, nanaian requested changes

2021-08-04 09:12 UTC, nanaian approved these changes

2021-08-04 09:12 UTC, merged