Rename all si_funcs to evt_funcs
pmret/papermario pull request #403
Opened 2021-08-28 17:05 UTC by Brotenko

resolve #397﻿

2021-08-28 17:08 UTC, ethteck requested changes

2021-08-28 17:08 UTC, ethteck commented on include/PR/rcp.h
> +#define EVT_BASE_REG		0x04800000
All changes to this file should be reverted since this is libultra

2021-08-28 17:46 UTC, BowserSlug commented
✅ This PR fixes 1 warnings!

2021-08-28 18:11 UTC, Brotenko commented
On @ethteck's request I will also rename every file in `evt.c` to have the `evt_` prefix

2021-08-28 20:34 UTC, nanaian commented
We should merge the other two open PRs before this one IMO & then ideally we can reapply the big rename to the new matches

2021-08-29 14:29 UTC, ethteck approved these changes

2021-08-29 14:34 UTC, merged