Match some bow funcs, a laki, and a chest func
pmret/papermario pull request #443
Opened 2021-09-26 22:44 UTC by ThreeMustyFears

2021-09-26 22:47 UTC, BowserSlug commented
🚀🚀🚀🚀🚀🚀🚀 This PR matches 7 functions (+0.13%) on `us`.

⚠️ This PR introduces 17 warnings:
- src/entity/Chest.c:153: warning: initialization from incompatible pointer type
- src/entity/Chest.c:169: warning: implicit declaration of function `entity_Chest_open'
- src/entity/Chest.c:229: warning: passing arg 6 of `playFX_1B' makes integer from pointer without a cast
- src/world/partner/bow.c:46: warning: assignment makes pointer from integer without a cast
- src/world/partner/lakilester.c:123: warning: initialization from incompatible pointer type
- src/world/partner/lakilester.c:36: warning: assignment makes pointer from integer without a cast
- src/world/partner/../../npc.h:185: warning: function declaration isn't a prototype
- src/world/partner/../../npc.h:189: warning: function declaration isn't a prototype
- src/world/partner/../../npc.h:210: warning: redundant redeclaration of `npc_dyn_entity_draw_no_op' in same scope
- src/world/partner/../../npc.h:259: warning: redundant redeclaration of `get_enemy' in same scope
- src/world/partner/../../npc.h:35: warning: redundant redeclaration of `get_npc_by_index' in same scope
- src/world/partner/../../npc.h:51: warning: function declaration isn't a prototype
- src/world/partner/../../npc.h:58: warning: redundant redeclaration of `npc_move_heading' in same scope
- src/world/partner/../../npc.h:60: warning: redundant redeclaration of `get_npc_unsafe' in same scope
- src/world/partner/../../npc.h:63: warning: redundant redeclaration of `get_npc_safe' in same scope
- src/world/partner/../../npc.h:81: warning: redundant redeclaration of `set_npc_yaw' in same scope

2021-09-26 22:53 UTC, ethteck requested changes

2021-09-26 22:53 UTC, ethteck commented on src/entity/Chest.c
> +            } else phi_f22 = 4.0f;
curly braces around this else please

2021-09-26 22:53 UTC, ethteck commented on src/world/partner/bow.c
> +s32 func_802BD694_323FE4(Evt* arg0, s32 arg1) {
arg0 = script, arg1 = isInitialCall

2021-09-26 22:53 UTC, ethteck commented on src/world/partner/bow.c
> +    if (arg1 != 0) {
!= 0 isn't needed for this bool check

2021-09-26 22:53 UTC, ethteck commented on src/world/partner/bow.c
> +    npc = arg0->owner2.npc;
npc can be initialized on the line where it's declared

2021-09-26 22:53 UTC, ethteck commented on src/world/partner/bow.c
> +                return 2;
ApiStatus_DONE2 (below as well)

2021-09-26 22:53 UTC, ethteck commented on src/world/partner/bow.c
> +                if (playerStatus->alpha1 < 0x81) {
<= 0x80

2021-09-26 22:53 UTC, ethteck commented on src/world/partner/bow.c
> +            if ((playerStatus->flags & 0x800) != 0) {
!= 0 and parens not needed

2021-09-26 22:53 UTC, ethteck commented on src/world/partner/bow.c
> +    playerStatus->alpha1 = 0xFF;
alphas can be in decimal (255)

2021-09-26 22:53 UTC, ethteck commented on src/world/partner/bow.c
> +    if ((playerStatus->flags & 0x800) != 0) {
!= 0 and parens can be removed

2021-09-26 22:53 UTC, ethteck commented on src/world/partner/bow.c
> +s32 func_802BDF08_324858(Evt* arg0, s32 arg1) {
standard script function signature (return ApiStatus, args, etc)

2021-09-26 22:53 UTC, ethteck commented on src/world/partner/bow.c
> +    if (arg1 != 0) {
Empty line after this, no need for != 0 for bool

2021-09-26 22:53 UTC, ethteck commented on src/world/partner/lakilester.c
> +s32 func_802BF4F0_323040(Evt* arg0, s32 arg1) {
Script func

2021-09-27 00:26 UTC, nanaian commented on src/world/partner/bow.c
> +    return partner_put_away(partner) != 0;
```suggestion
    if (partner_put_away(partner)) {
        return ApiStatus_DONE1;
    } else {
        return ApiStatus_BLOCK;
    }
```

2021-09-27 00:26 UTC, nanaian commented on src/world/partner/bow.c
> +    if (D_802BE0C0 != 0) {
This seems to be a bool?
```suggestion
    if (D_802BE0C0) {
```

2021-09-27 00:26 UTC, nanaian commented on src/world/partner/bow.c
> +        D_802BE0C0 = 0;
```suggestion
        D_802BE0C0 = FALSE;
```

2021-09-27 00:26 UTC, nanaian commented on src/world/partner/lakilester.c
> +        D_802BFF00 = phi_v1;
If it matches,
```suggestion
        if (D_802BFF0C == 0) {
            D_802BFF00 = 3;
        } else {
            D_802BFF00 = 0;
        }
```

2021-09-27 00:26 UTC, nanaian commented on src/world/partner/lakilester.c
> +                D_802BFF08 = 0;
Bool?

2021-09-27 00:38 UTC, ethteck approved these changes

2021-09-27 00:42 UTC, nanaian commented on src/world/partner/lakilester.c
>          D_802BFF00 = phi_v1;
Oh does a ternary work?

2021-09-27 00:46 UTC, ThreeMustyFears commented on src/world/partner/lakilester.c
>          D_802BFF00 = phi_v1;
Yeah it seems to

2021-09-27 01:00 UTC, merged