Decomp pause_sort_item_list and pause_draw_rect
pmret/papermario pull request #453
Opened 2021-09-30 22:57 UTC by Dalrik

pause_sort_item_list is a very ugly match, I feel like the original code would have been based on indices instead of pointer arithmetic, especially given the optimization behavior around the do/while loop (I think the second half of the condition might avoid optimization if it's looking at indices), but I couldn't find anything that works. https://decomp.me/scratch/TRZek if you want to explore.

This also has close matches on two other functions in 135EE0, only issue with each is delay slot related and would probably be fixed by adding a data section.

2021-09-30 23:01 UTC, BowserSlug commented
🚀🚀 This PR matches 2 functions (+0.02%) on `us`.

2021-10-01 01:22 UTC, ethteck requested changes

2021-10-01 01:22 UTC, ethteck commented on src/pause/135EE0.c
> +                if ((parent == -1 || parent == 0x16) && (window->flags & 8) != 0) {
!= 0 unneeded for flag check

2021-10-01 01:22 UTC, ethteck commented on src/pause/135EE0.c
> +    } else if ((window->flags & 8) == 0 && (window->parent == -1 || (gWindows[window->parent].flags & 8) == 0)) {
`!(gWindows[window->parent].flags & 8)`

2021-10-01 01:22 UTC, ethteck commented on src/pause/135EE0.c
> +    } else if ((window->flags & 8) == 0 && (window->parent == -1 || (gWindows[window->parent].flags & 8) == 0)) {
! for flag checks

2021-10-01 01:22 UTC, ethteck commented on src/pause/135EE0.c
> +    if (ulx < -2687 || uly < -2687 || lrx <= 0 || lry <= 0) {
<= -2688 for these? (so the numbers match the second one)

2021-10-01 10:59 UTC, ethteck approved these changes

2021-10-01 11:13 UTC, nanaian approved these changes

2021-10-01 11:14 UTC, merged