Various C file decomp
pmret/papermario pull request #501
Opened 2021-10-27 14:19 UTC by Rainchus

2021-10-30 12:42 UTC, nanaian requested changes
Hopefully the last review!

2021-10-30 12:42 UTC, nanaian commented on src/world/area_nok/nok_04/9EDBF0.c
> +} Unk80241440_2; //sizeof 0x44
```suggestion
} Unk80241440_2; // size = 0x44
```

2021-10-30 12:42 UTC, nanaian commented on src/world/area_nok/nok_04/9EDBF0.c
> +} Unk80241440; //sizeof 0x48
```suggestion
} Unk80241440; // size = 0x48
```

2021-10-30 12:42 UTC, nanaian commented on src/world/partner/lakilester.c
> +f64 fabs(f64 temp);
I'd be surprised if this wasn't declared already? (by libultra)

2021-10-30 12:42 UTC, nanaian commented on src/world/partner/lakilester.c
> +        D_8010C954 = 0;
```suggestion
        D_8010C954 = NULL;
```

2021-10-30 12:42 UTC, nanaian commented on src/world/partner/lakilester.c
> +    if (D_8010C954 != 0) {
This is a pointer
```suggestion
    if (D_8010C954 != NULL) {
```

2021-10-30 12:42 UTC, nanaian commented on src/world/partner/lakilester.c
> +        if ((temp_f24 * temp_f24) + (temp_f26 * temp_f26) > 3025.0f) {
```suggestion
        if (SQ(temp_f24) + SQ(temp_f26) > 3025.0f) {
```

2021-10-30 12:42 UTC, nanaian commented on src/world/partner/lakilester.c
> +        playerStatus->animFlags &= 0xDFFFFFFF;
this is unresolved

2021-10-30 12:42 UTC, nanaian commented on src/world/partner/lakilester.c
> +#endif
damn. good effort

2021-10-30 12:42 UTC, nanaian commented on src/world/partner/lakilester.c
> +            set_action_state(0x21);
Can you use the actionstate enum

2021-10-30 12:42 UTC, nanaian commented on src/world/partner/lakilester.c
> +                set_action_state(0x21);
Use enum

2021-10-30 12:42 UTC, nanaian commented on src/world/partner/lakilester.c
> +                    set_action_state(0x21);
Use enum

2021-10-31 07:12 UTC, ethteck commented on src/759b0_len_61b0.c
> +        if ((temp_f0 > 60.0f) && (temp_f0 < 90.0f)) {
still unnecessary parens for the tempf0 greater than / less than conditions

2021-11-01 00:56 UTC, nanaian approved these changes

2021-11-01 08:06 UTC, merged