Msg header file
pmret/papermario pull request #517
Opened 2021-11-03 02:44 UTC by Ponmander

I thought I might as well start this pull request.
I KNOW THERE ARE ERRORS I NEED HELP.
Please help me it has had me stumped for days I checked all the files that contain the variables/structs that are from this new header file so I would include `msg.h`

2021-11-03 02:48 UTC, BowserSlug commented
🚀 This PR matches 1 function (+0.00%) on `us`.

2021-11-03 09:41 UTC, nanaian requested changes
There is data in the header files which should not be there - it'll be redefined for every place the header file is included!

I'd suggest moving all data back to where it was in C files and only defining functions for the time being. It's less error-prone and will avoid mistakenly putting BSS-to-be symbols in header files

2021-11-03 21:18 UTC, Brotenko requested changes
You have a bunch of redundant function declarations that result in the ROM not building. You'll have to resolve these in some form or another (either removing them from the fio.h file, or removing them from functions.h, or some mix of those) 
![grafik](https://user-images.githubusercontent.com/31699028/140194198-d983a998-e9dc-414b-b644-6e74d326bbf6.png)

2021-11-03 22:27 UTC, Ponmander commented
Here's the 4th push.

2021-11-07 07:03 UTC, ethteck commented
> You have a bunch of redundant function declarations that result in the ROM not building. You'll have to resolve these in some form or another (either removing them from the fio.h file, or removing them from functions.h, or some mix of those) ![grafik](https://user-images.githubusercontent.com/31699028/140194198-d983a998-e9dc-414b-b644-6e74d326bbf6.png)

These are just warnings and aren't related to the rom not building

2021-11-10 11:04 UTC, JoshDuMan commented on src/msg.h
> +s16 MessageSingular;
These two are not externed. This may be why the build is failing.

2021-11-11 08:50 UTC, ethteck commented
Closing as discussed on discord

2021-11-11 08:50 UTC, closed without merging