Match deduct_current_move_fp
pmret/papermario pull request #521
Opened 2021-11-05 16:45 UTC by JoshDuMan

2021-11-05 16:51 UTC, JoshDuMan commented
https://decomp.me/scratch/7Pi18

2021-11-05 16:53 UTC, BowserSlug commented
🚀 This PR matches 1 function (+0.00%) on `us`.

2021-11-06 13:33 UTC, nanaian approved these changes

2021-11-06 13:33 UTC, nanaian reviewed
Actually I'd spread these lines out a lil bit based on which actor is being reset

2021-11-06 13:33 UTC, nanaian commented on src/190B20.c
> +    actor = battleStatus->partnerActor;
```suggestion

    actor = battleStatus->playerActor;
    actor->hpChangeCounter = 0;
    actor->damageCounter = 0;
    actor->unk_204[0] = 0;
    
    actor = battleStatus->partnerActor;
```

2021-11-07 06:59 UTC, ethteck requested changes

2021-11-07 06:59 UTC, ethteck commented on src/190B20.c
> +    playerData->curFP = playerData->curFP - fpCost;
-=

2021-11-07 06:59 UTC, ethteck commented on src/190B20.c
> +    actor = battleStatus->playerActor;
Do you actually have to keep saving the current actor into this temp? You can't just do battleStatus->playerActor-> whatever = 0?

2021-11-07 06:59 UTC, ethteck commented on src/190B20.c
> +    actor = battleStatus->playerActor;
nm. tried it and you can't.

2021-11-07 09:20 UTC, merged