Match func_80263914
pmret/papermario pull request #523
Opened 2021-11-08 04:09 UTC by JoshDuMan

2021-11-08 08:20 UTC, ethteck requested changes

2021-11-08 08:20 UTC, ethteck commented on src/190B20.c
> +    battleStatus->submenuMoves[0] = playerData->currentPartner * 6 +  0x7D + partner->staticActorData->level;
```suggestion
    battleStatus->submenuMoves[0] = playerData->currentPartner * 6 + 0x7D + partner->staticActorData->level;
```

2021-11-08 08:20 UTC, ethteck commented on src/190B20.c
> +    phi_s6 = 0;
FALSE

2021-11-08 08:20 UTC, ethteck commented on src/190B20.c
> +                phi_s6 = 1;
TRUE

2021-11-08 08:20 UTC, ethteck commented on src/190B20.c
> +    if (phi_s6 == 0) {
!phi_s6

2021-11-08 22:20 UTC, Brotenko reviewed
LGTM after implementing Ethan's requested changes!

2021-11-09 03:13 UTC, BowserSlug commented
🚀 This PR matches 1 function (+0.01%) on `us`.

2021-11-09 03:17 UTC, ethteck approved these changes

2021-11-10 10:47 UTC, Brotenko approved these changes

2021-11-10 18:57 UTC, nanaian approved these changes

2021-11-10 18:57 UTC, merged