Decompile misc battle map funcs
pmret/papermario pull request #528
Opened 2021-11-12 22:54 UTC by Brotenko

- Match msg_get_glyph (#497)
- Match calc_enemy_test_target (#499)
- Add sprite.h (#503)
- B4580 and d0a70_len_4fe0 (#502)
- decompile several map and battle-map related functions (#504)
- Header file for fio (#505)
- use is_debug.c on jp (#507)
- Share 1370.c across versions (#509)
- Match check_conversation_trigger (#508)
- Match CreatePartShadow & RemovePartShadow (#511)
- Match SummonEnemy & UseIdleAnimation (#510)
- Changes required to prevent kmc compiler from using debugging (#514)
- Various C file decomp (#501)
- Match RemoveActorDecoration, AddActorDecoration, GetDistanceToGoal (#513)
- Add descriptions to all map headers (#515)
- Match ModifyActorDecoration, func_8026EA7C, get_coin_drop_amount (#516)
- Match count_power_plus (#518)
- Match _heap_malloc and _heap_malloc_tail (#519)
- Match deduct_current_move_fp (#521)
- Match _heap_free (#522)
- Match attack submenus (#523)
- Update flags and enums in enums.h (#525)
- match _heap_realloc (#524)
- Match StartBossBattle (#526)
- . (#527)
- appendGfx_message (#520)
- .
- .

2021-11-12 22:56 UTC, BowserSlug commented
🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀 This PR matches 13 functions (+0.05%) on `us`.

⚠️ This PR introduces 5 warnings:
- src/battle/area_trd_part_2/4B11F0.c:18: warning: implicit declaration of function `bgm_set_battle_song'
- src/battle/area_trd_part_2/4B11F0.c:19: warning: implicit declaration of function `bgm_push_battle_song'

2021-11-13 03:13 UTC, ethteck requested changes

2021-11-13 03:13 UTC, ethteck commented on src/battle/area_trd_part_2/4B2550.c
> +//INCLUDE_ASM(s32, "battle/area_trd_part_2/4B2550", dup4_b_area_trd_part_2_UnkEnemyFunc);
this comment can go bye bye

2021-11-13 03:13 UTC, ethteck commented on src/common/UnkWhirlwindEffectFunc.inc.c
> +    playFX_46_whirlwind(6, (s32) &effectStruct, 1.0f, var4);
Could you rename this struct to `EffectWhirlwind`? The struct should go into effects.h and the signature of playFX_46_whirlwind should be changed to take a `EffectWhirlwind*`

2021-11-13 11:16 UTC, ethteck approved these changes

2021-11-14 20:18 UTC, nanaian approved these changes
Here's betting UnkEnemyFunc is used for finding this first of the Koopa Bros. that is not on the floor

2021-11-14 20:20 UTC, Brotenko commented
> 
> 
> Here's betting UnkEnemyFunc is used for finding the first of the Koopa Bros. that is not on the floor

Well, it has something to do with the Koopa Bros. for sure, that much is certain

2021-11-14 20:23 UTC, merged