Kooper.c
pmret/papermario pull request #537
Opened 2021-11-19 12:57 UTC by Ponmander

2021-11-19 13:03 UTC, ethteck requested changes
Nice job! One more thing: it makes more sense to name this PR the name of the function you decomped, instead of the file it came from. If you were doing more functions in this file, then the current name would make more sense. but since it's just one, better to be specific. you can rename the PR with the "edit" button

2021-11-19 13:03 UTC, ethteck commented on src/world/partner/kooper.c
> +extern s32 D_802BEC54;
Externs are typically put at the top of the file with eachother. This one would go before the unkPartnerStruct* one at the very top, to put them in ram order.

2021-11-19 13:03 UTC, ethteck commented on src/world/partner/kooper.c
> +//INCLUDE_ASM(s32, "world/partner/kooper", func_802BD200_31B220);
This comment can be removed

2021-11-19 13:03 UTC, ethteck commented on src/world/partner/kooper.c
> +    npc->collisionHeight = 0x25;
The height and radius values should be written in decimal

2021-11-19 13:07 UTC, Brotenko commented
Nothing to add besides Ethan's comments! Just make sure to run ./coverage.py before you push the requested changes and you should be golden - Good job!

2021-11-19 13:59 UTC, nanaian reviewed
Nothing to add, gj

2021-11-20 12:33 UTC, ethteck commented
I made the requested changes and am merging them since Ponderman said he's too busy to currently

2021-11-20 12:34 UTC, ethteck commented
Nevermind, this is already done by Rain

2021-11-20 12:34 UTC, closed without merging