Match func_8026EBF8 and LoadItemScript
pmret/papermario pull request #543
Opened 2021-12-02 07:49 UTC by JoshDuMan

2021-12-02 07:50 UTC, JoshDuMan commented
LoadItemScript - https://decomp.me/scratch/ERRgD
func_8026EBF8 - https://decomp.me/scratch/zGMkp

2021-12-02 07:52 UTC, BowserSlug commented
🚀🚀 This PR matches 2 functions (+0.02%) on `us`.

⚠️ This PR introduces a warning:
- src/1967B0.c:60: warning: assignment makes integer from pointer without a cast
- src/1967B0.c:72: warning: passing arg 1 of `dma_copy' makes pointer from integer without a cast
- src/1967B0.c:72: warning: passing arg 2 of `dma_copy' makes pointer from integer without a cast
- src/1967B0.c:72: warning: passing arg 3 of `dma_copy' makes pointer from integer without a cast
- src/1967B0.c:78: warning: implicit declaration of function `enable_player_blur'
- src/197F40.c:2402: warning: implicit declaration of function `func_80266E40'
- src/197F40.c:2539: warning: implicit declaration of function `remove_player_buffs'
- src/197F40.c:2629: warning: initialization makes pointer from integer without a cast
- src/197F40.c:2633: warning: comparison between pointer and integer
- src/197F40.c:2634: warning: assignment makes pointer from integer without a cast
- src/197F40.c:2638: warning: passing arg 1 of `get_actor' makes integer from pointer without a cast
- src/197F40.c:2640: warning: implicit declaration of function `is_actor_hp_bar_visible'
- src/197F40.c:2641: warning: implicit declaration of function `load_tattle_flags'
- src/197F40.c:2656: warning: implicit declaration of function `func_80251474'

2021-12-02 08:39 UTC, ethteck requested changes

2021-12-02 08:39 UTC, ethteck commented on include/common_structs.h
> +    /* 0x6D8 */ char unk_6D8[0x67];
this should be 0x68

2021-12-02 08:39 UTC, ethteck commented on src/1967B0.c
> +        if ((s8) battleStatus->itemUsesLeft == 2) {
Can we make this an s8 to avoid the cast?

2021-12-03 03:59 UTC, ethteck approved these changes

2021-12-03 07:54 UTC, ethteck approved these changes

2021-12-03 18:27 UTC, nanaian requested changes

2021-12-03 18:27 UTC, nanaian commented on src/1967B0.c
> +        if (*itemPtr == battleStatus->selectedItemID){
```suggestion
        if (*itemPtr == battleStatus->selectedItemID) {
```

2021-12-03 18:28 UTC, ethteck commented on src/1967B0.c
> +        if (*itemPtr == battleStatus->selectedItemID){
ohh nice, nabbed 'em

2021-12-04 04:34 UTC, merged