Decomp misc funcs
pmret/papermario pull request #546
Opened 2021-12-10 22:37 UTC by Brotenko

- Match msg_get_glyph (#497)
- Match calc_enemy_test_target (#499)
- Add sprite.h (#503)
- B4580 and d0a70_len_4fe0 (#502)
- decompile several map and battle-map related functions (#504)
- Header file for fio (#505)
- use is_debug.c on jp (#507)
- Share 1370.c across versions (#509)
- Match check_conversation_trigger (#508)
- Match CreatePartShadow & RemovePartShadow (#511)
- Match SummonEnemy & UseIdleAnimation (#510)
- Changes required to prevent kmc compiler from using debugging (#514)
- Various C file decomp (#501)
- Match RemoveActorDecoration, AddActorDecoration, GetDistanceToGoal (#513)
- Add descriptions to all map headers (#515)
- Match ModifyActorDecoration, func_8026EA7C, get_coin_drop_amount (#516)
- Match count_power_plus (#518)
- Match _heap_malloc and _heap_malloc_tail (#519)
- Match deduct_current_move_fp (#521)
- Match _heap_free (#522)
- Match attack submenus (#523)
- Update flags and enums in enums.h (#525)
- match _heap_realloc (#524)
- Match StartBossBattle (#526)
- . (#527)
- appendGfx_message (#520)
- Decompile even more misc battle map funcs (#531)
- Decompile misc battle map funcs (#528)
- Make a 224 functions show up in the elf (#530)
- Update .clang-tidy (#533)
- Match some 16F740 funcs (#532)
- Propose new stuff for ifdefs (#534)
- replaced commented out with if-0s (#529)
- fold_* , effect_10, and other assorted decomp (#535)
- match functions in world partner files for lakilester, watt, sushie (#536)
- Use designated inits for data tables and AC 0A data migration (#538)
- Cleaned up some code related to u32->f32 casts (#539)
- Match all FX render functions (#540)
- Match func_8026EBF8, LoadFreeItemScript, and LoadItemScript (#543)
- Cleanup charge moves (#542)
- Match check_for_ispy and check_for_pulse_stone (#544)
- Match more overworld partner functions (#541)
- decomp misc funcs
- cleanup on MakeShop and initial work on ShowShopOwnerDialog
- match ShowShopOwnerDialog
- decomp misc funcs
- cleanup on MakeShop and initial work on ShowShopOwnerDialog
- match ShowShopOwnerDialog

2021-12-10 22:39 UTC, BowserSlug commented
🚀🚀🚀🚀 This PR matches 4 functions (+0.09%) on `us`.

⚠️ This PR introduces 14 warnings:
- src/world/partners.c:113: warning: initialization makes pointer from integer without a cast
- src/world/partners.c:115: warning: initialization makes pointer from integer without a cast
- src/world/partners.c:119: warning: initialization makes pointer from integer without a cast
- src/world/partners.c:131: warning: initialization makes pointer from integer without a cast
- src/world/partners.c:136: warning: initialization makes pointer from integer without a cast
- src/world/partners.c:148: warning: initialization makes pointer from integer without a cast
- src/world/partners.c:152: warning: initialization makes pointer from integer without a cast
- src/world/partners.c:177: warning: initialization makes pointer from integer without a cast
- src/world/partners.c:182: warning: initialization makes pointer from integer without a cast
- src/world/partners.c:194: warning: initialization makes pointer from integer without a cast
- src/world/partners.c:199: warning: initialization makes pointer from integer without a cast
- src/world/partners.c:211: warning: initialization makes pointer from integer without a cast
- src/world/partners.c:216: warning: initialization makes pointer from integer without a cast
- src/world/partners.c:228: warning: initialization makes pointer from integer without a cast
- src/world/partners.c:232: warning: initialization makes pointer from integer without a cast
- src/world/partners.c:271: warning: missing braces around initializer for `gPartnerAnimations[0].anims'
- src/world/partners.c:282: warning: initialization makes pointer from integer without a cast
- src/world/partners.c:282: warning: initialization makes pointer from integer without a cast
- src/world/partners.c:282: warning: initialization makes pointer from integer without a cast
- src/world/partners.c:282: warning: initialization makes pointer from integer without a cast
- src/world/partners.c:282: warning: initialization makes pointer from integer without a cast
- src/world/partners.c:282: warning: initialization makes pointer from integer without a cast
- src/world/partners.c:282: warning: initialization makes pointer from integer without a cast
- src/world/partners.c:282: warning: initialization makes pointer from integer without a cast
- src/world/partners.c:282: warning: initialization makes pointer from integer without a cast
- src/world/partners.c:285: warning: excess elements in scalar initializer after `D_800F84F8'
- src/world/partners.c:292: warning: passing arg 1 of `dma_copy' makes pointer from integer without a cast
- src/world/partners.c:292: warning: passing arg 2 of `dma_copy' makes pointer from integer without a cast
- src/world/partners.c:293: warning: passing arg 1 of `start_script' makes pointer from integer without a cast
- src/world/partners.c:609: warning: passing arg 1 of `start_script' from incompatible pointer type
- src/world/partners.c:669: warning: assignment from incompatible pointer type
- src/world/partners.c:677: warning: assignment from incompatible pointer type
- src/world/partners.c:729: warning: assignment from incompatible pointer type
- src/world/partners.c:736: warning: assignment from incompatible pointer type
- src/world/partners.c:76: warning: initialization makes integer from pointer without a cast
- src/world/partners.c:76: warning: initialization makes integer from pointer without a cast
- src/world/partners.c:792: warning: assignment makes integer from pointer without a cast
- src/world/partners.c:800: warning: assignment makes integer from pointer without a cast
- src/world/partners.c:816: warning: assignment makes integer from pointer without a cast
- src/world/partners.c:892: warning: initialization from incompatible pointer type
- src/world/script_api/7E0E80.c:100: warning: assignment makes integer from pointer without a cast
- src/world/script_api/7E0E80.c:102: warning: assignment makes integer from pointer without a cast
- src/world/script_api/7E0E80.c:107: warning: passing arg 1 of `start_script' from incompatible pointer type
- src/world/script_api/7E0E80.c:119: warning: passing arg 1 of `start_script' from incompatible pointer type
- src/world/script_api/7E0E80.c:131: warning: passing arg 1 of `start_script' from incompatible pointer type
- src/world/script_api/7E0E80.c:168: warning: implicit declaration of function `func_800E98EC'
- src/world/script_api/7E0E80.c:178: warning: passing arg 1 of `start_script' from incompatible pointer type
- src/world/script_api/7E0E80.c:211: warning: implicit declaration of function `func_800E9900'
- src/world/script_api/7E0E80.c:223: warning: implicit declaration of function `show_coin_counter'
- src/world/script_api/7E0E80.c:241: warning: implicit declaration of function `add_item'
- src/world/script_api/7E0E80.c:247: warning: implicit declaration of function `add_badge'
- src/world/script_api/7E0E80.c:24: warning: initialization makes integer from pointer without a cast
- src/world/script_api/7E0E80.c:26: warning: initialization makes integer from pointer without a cast
- src/world/script_api/7E0E80.c:28: warning: initialization makes integer from pointer without a cast
- src/world/script_api/7E0E80.c:28: warning: initialization makes integer from pointer without a cast
- src/world/script_api/7E0E80.c:293: warning: assignment from incompatible pointer type
- src/world/script_api/7E0E80.c:308: warning: implicit declaration of function `func_800E96C8'
- src/world/script_api/7E0E80.c:30: warning: initialization makes integer from pointer without a cast
- src/world/script_api/7E0E80.c:32: warning: initialization makes integer from pointer without a cast
- src/world/script_api/7E0E80.c:32: warning: initialization makes integer from pointer without a cast
- src/world/script_api/7E0E80.c:32: warning: initialization makes integer from pointer without a cast
- src/world/script_api/7E0E80.c:34: warning: initialization makes integer from pointer without a cast
- src/world/script_api/7E0E80.c:34: warning: initialization makes integer from pointer without a cast
- src/world/script_api/7E0E80.c:387: warning: implicit declaration of function `hide_popup_menu'
- src/world/script_api/7E0E80.c:399: warning: implicit declaration of function `destroy_popup_menu'
- src/world/script_api/7E0E80.c:39: warning: passing arg 1 of `start_script' from incompatible pointer type
- src/world/script_api/7E0E80.c:401: warning: implicit declaration of function `func_800E98C4'
- src/world/script_api/7E0E80.c:453: warning: implicit declaration of function `get_item_count'
- src/world/script_api/7E0E80.c:467: warning: implicit declaration of function `get_stored_empty_count'
- src/world/script_api/7E0E80.c:476: warning: implicit declaration of function `get_stored_count'
- src/world/script_api/7E0E80.c:481: warning: implicit declaration of function `get_item_empty_count'
- src/world/script_api/7E0E80.c:498: warning: implicit declaration of function `shop_open_item_select_popup'
- src/world/script_api/7E0E80.c:539: warning: implicit declaration of function `hide_coin_counter'
- src/world/script_api/7E0E80.c:55: warning: implicit declaration of function `set_message_msg'
- src/world/script_api/7E0E80.c:56: warning: implicit declaration of function `set_message_value'
- src/world/script_api/7E0E80.c:587: warning: implicit declaration of function `store_item'
- src/world/script_api/7E0E80.c:62: warning: assignment makes integer from pointer without a cast
- src/world/script_api/7E0E80.c:64: warning: assignment makes integer from pointer without a cast
- src/world/script_api/7E0E80.c:691: warning: implicit declaration of function `open_status_menu_short'
- src/world/script_api/7E0E80.c:69: warning: passing arg 1 of `start_script' from incompatible pointer type
- src/world/script_api/7E0E80.c:714: warning: function declaration isn't a prototype
- src/world/script_api/7E0E80.c:81: warning: passing arg 1 of `start_script' from in [...]

2021-12-11 02:57 UTC, ethteck requested changes
Great job!

2021-12-11 02:57 UTC, ethteck commented on src/world/partners.c
> +        if ((arg0 & 0x4000) != 0) {
No != 0 and extra parens needed

2021-12-11 02:57 UTC, ethteck commented on src/world/partners.c
> +    } else {
I think this would be better as an else if (arg0 == 4) ...

2021-12-11 02:57 UTC, ethteck commented on src/world/script_api/7E0E80.c
> +            bpCost = D_8008F072[shopItem->moveID * 0x14];
This looks suspiciously like an array of structs size 0x14, and from the star rod database:
`58:dat : 8008F060 : MoveTable : move_table_entry[185`]`

so actually, this should be `gMoveTable[shopItem->moveID].costBP`

2021-12-11 02:57 UTC, ethteck commented on src/world/script_api/7E0E80.c
> +            if (does_script_exist(script->functionTemp[1]) == 0) {
all these does_script_exist checks are bool checks, so these can be ! instead of == 0

2021-12-11 02:57 UTC, ethteck commented on src/world/script_api/7E0E80.c
> +            if (does_script_exist(script->functionTemp[1]) == 0) {
same in this func

2021-12-11 02:57 UTC, ethteck commented on src/world/script_api/7E0E80.c
> +        default:
You probably don't need the default case if it's just break

2021-12-11 16:37 UTC, ethteck approved these changes

2021-12-15 14:52 UTC, nanaian requested changes
1 nit, gud matches otherwise. The logic in func_800EA52C seems a bit iffy but it's totally possible it was written that way :shipit:

2021-12-15 14:52 UTC, nanaian commented on src/world/script_api/7E0E80.c
> +            if (does_script_exist(script->functionTemp[1]) == 0) {
```suggestion
            if (!does_script_exist(script->functionTemp[1])) {
```

2021-12-15 19:08 UTC, nanaian approved these changes

2021-12-15 19:12 UTC, merged