Match actor_api.c
pmret/papermario pull request #585
Opened 2021-12-28 17:56 UTC by JoshDuMan

2021-12-28 17:58 UTC, BowserSlug commented
🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀 This PR matches 14 functions (+0.10%) on `us`.

✅ This PR fixes 12 warnings!

2021-12-28 23:10 UTC, nanaian requested changes
0.1%, gg.

Please also name this file src/**evt**/actor_api.c

2021-12-28 23:10 UTC, nanaian commented on src/actor_api.c
> +    s32 temp2 = *args++;
Are these required? If not can you name them & `temp_s2`

2021-12-28 23:10 UTC, nanaian commented on src/actor_api.c
> +
Remove this newline

2021-12-29 04:09 UTC, ethteck requested changes
Great work here! The only other thing I'd say is that I bet some of the temps in ChooseNextTarget are unnecessary. but no worries if you can't remove any of them.

2021-12-29 04:09 UTC, ethteck commented on src/actor_api.c
> +        phi_v1_4 = actor->targetIndexList[ actor->selectedTargetIndex];
```suggestion
        phi_v1_4 = actor->targetIndexList[actor->selectedTargetIndex];
```

2021-12-29 04:09 UTC, ethteck commented on src/actor_api.c
> +    target = &actor->targetData[actor->targetIndexList[(s8) phi_v1]];
is this cast needed? maybe the type should be different?

2021-12-29 12:22 UTC, merged