Script clean-up
pmret/papermario pull request #586
Opened 2021-12-28 18:35 UTC by Brotenko

2021-12-28 23:12 UTC, nanaian requested changes
I personally don't see the point of removing tools that work fine..

2021-12-28 23:12 UTC, nanaian commented on tools/fix_s_filenames.py
> -                os.rename(f_path, new_f_path)
I'd prefer to keep this

2021-12-28 23:12 UTC, nanaian commented on tools/mv_segment.py
> -    os.rename(f"ver/current/asm/data/{args.src}.rodata.s", f"ver/current/asm/data/{args.dest}.rodata.s")
I'd prefer to keep this

2021-12-29 00:52 UTC, Brotenko commented on tools/fix_s_filenames.py
> -                os.rename(f_path, new_f_path)
Fine by me if you still use/need it!

2021-12-29 00:52 UTC, Brotenko commented on tools/mv_segment.py
> -    os.rename(f"ver/current/asm/data/{args.src}.rodata.s", f"ver/current/asm/data/{args.dest}.rodata.s")
Fine by me if you still use/need it!

2021-12-29 01:34 UTC, closed without merging