names etc
pmret/papermario pull request #595
Opened 2021-12-30 16:08 UTC by HailSanta

names for a few fields in game status

2021-12-30 16:10 UTC, Brotenko approved these changes
LGTM to me

2021-12-31 00:38 UTC, nanaian commented on include/common_structs.h
> +    /* 0x0AB */ u8 usingStereoSound;
If this is a bool I'd prefix with `is`...
```suggestion
    /* 0x0AB */ u8 isUsingStereoSound;
```
Or
```suggestion
    /* 0x0AB */ u8 isStereo;
```

2021-12-31 00:40 UTC, nanaian requested changes

2021-12-31 00:40 UTC, nanaian commented on src/rumble.c
> +s32 RumbleButtons = 0;
These should be lowerCamelCase, and possibly prefixed like `rumble_maxDuration` and `rumble_buttons`

2022-01-01 09:09 UTC, ethteck approved these changes
Happy after the existing stuff is addressed. Thanks :)

2022-01-01 10:14 UTC, nanaian commented on src/rumble.c
> +s32 RumbleButtons = 0;
@ethteck do you think we should prefix it like rumble_ or just rumbleMaxDuration

2022-01-01 13:09 UTC, BowserSlug commented
✅ This PR fixes 49 warnings!

2022-01-02 06:01 UTC, nanaian requested changes
Sorry for not catching these before

2022-01-02 06:01 UTC, nanaian commented on src/165490.c
> +    if (gGameStatusPtr->isUsingStereoSound == 1) {
```suggestion
    if (gGameStatusPtr->isUsingStereoSound) {
```

2022-01-02 06:01 UTC, nanaian commented on src/165490.c
> +    if (gGameStatusPtr->isUsingStereoSound == 0) {
```suggestion
    if (!gGameStatusPtr->isUsingStereoSound) {
```

2022-01-02 06:01 UTC, nanaian commented on src/state_startup.c
> +        gGameStatusPtr->isUsingStereoSound = 1;
```suggestion
        gGameStatusPtr->isUsingStereoSound = TRUE;
```

2022-01-02 06:01 UTC, nanaian commented on src/state_startup.c
> +        gGameStatusPtr->isUsingStereoSound = 0;
```suggestion
        gGameStatusPtr->isUsingStereoSound = FALSE;
```

2022-01-03 09:56 UTC, merged