Fix a few warnings
pmret/papermario pull request #601
Opened 2022-01-02 22:52 UTC by JoshDuMan

2022-01-02 22:56 UTC, BowserSlug commented
✅ This PR fixes 624 warnings!

2022-01-02 23:47 UTC, nanaian approved these changes
ty

2022-01-02 23:47 UTC, nanaian commented on .vscode/c_cpp_properties.json
> +                "${workspaceFolder}/include/script_api",
Why?

2022-01-03 09:53 UTC, ethteck requested changes
great work! couple tiny things

2022-01-03 09:53 UTC, ethteck commented on ver/us/undefined_syms.txt
> +dead_guMtxIdentF = 0x8006c660;
uppercase address please

2022-01-03 09:53 UTC, ethteck commented on src/EF2680.c
> +    NpcAISettings* aiSettings =(NpcAISettings*) evt_get_variable(script, *args);
spcae after =

2022-01-03 17:36 UTC, merged