Match collision functions
pmret/papermario pull request #609
Opened 2022-01-07 15:55 UTC by Unnunu

2022-01-07 15:57 UTC, BowserSlug commented
🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀 This PR matches 13 functions (+0.30%) on `us`.

✅ This PR fixes 1 warnings!

2022-01-07 16:47 UTC, nanaian requested changes
Awesome decomp & documentation work, especially for a first contribution! Thank you!
I've made a few comments on where your style deviates from the existing codebase - if you could fix them across `collision.c` that'd be great

2022-01-07 16:47 UTC, nanaian commented on src/collision.c
> +{
Hia, we use this brace style:
```suggestion
void backup_map_collision_data(void) {
```

2022-01-07 16:47 UTC, nanaian commented on src/collision.c
> +    CollisionData *pCollisionData;
Align pointer asterisks to the left:
```suggestion
    CollisionData* pCollisionData;
```

2022-01-07 16:47 UTC, nanaian commented on src/collision.c
> +
Empty line here not needed

2022-01-07 16:47 UTC, nanaian commented on src/collision.c
> +        numTrianles = pCollider->numTriangles;
Typo
```suggestion
        numTriangles = pCollider->numTriangles;
```

2022-01-07 19:39 UTC, nanaian requested changes

2022-01-07 19:39 UTC, nanaian commented on src/collision.c
> +         pAssetBoundingBox++, pBoundingBox++, i++) {
Looks like you have an extra space of indentation here

2022-01-07 19:39 UTC, nanaian commented on src/collision.c
> +         pVertices++, pAssetVertices++, i++) {
& here

2022-01-08 00:04 UTC, nanaian approved these changes

2022-01-08 05:58 UTC, ethteck requested changes
Amazing work, and welcome to the project! Just a few more style things I noticed. also, I'm asking @HailSanta to look over name changes and make sure he agrees with them or prefers different / the existing names he has.

By the way, what does the p prefix for locals that you're using mean?

2022-01-08 05:58 UTC, ethteck commented on src/collision.c
> +} HitAsset;
Having offset / size comments for these would be nice, as we do for other structs (see common_structs.h)

2022-01-08 05:58 UTC, ethteck commented on src/collision.c
> +typedef struct {
This struct def and these externs should be at the top with the others (externs in ram order too please)

2022-01-08 09:11 UTC, Unnunu commented
Put struct defs and externs to the right place and also corrected the names. And p is for pointer. Should I remove it?

2022-01-08 09:29 UTC, ethteck commented
Yeah, I'd remove it since we don't do that elsewhere and I find those kinds of prefixes more annoying than useful in practice, personally. Thanks for making the other changes!

2022-01-08 10:11 UTC, merged