Match two functions in 23680.c
pmret/papermario pull request #624
Opened 2022-01-15 08:01 UTC by JoshDuMan

2022-01-15 08:07 UTC, BowserSlug commented
🚀🚀 This PR matches 2 functions (+0.05%) on `us`.

2022-01-15 08:13 UTC, ethteck requested changes

2022-01-15 08:13 UTC, ethteck commented on include/npc.h
> +    /* 0xAC */ u8 unk_AC;
3 bytes of padding should be added here from AD to AF

2022-01-15 08:13 UTC, ethteck commented on src/23680.c
> +        return 0;
the 0s and 1s can be FALSE and TRUE here

2022-01-16 05:19 UTC, ethteck approved these changes

2022-01-16 13:31 UTC, nanaian approved these changes

2022-01-16 13:32 UTC, merged