Decompiled and Matched func_802A10A4_77F2E4
pmret/papermario pull request #662
Opened 2022-03-16 16:55 UTC by Nasina7

I've done a good amount of emudev work before, but this is my first time decompiling anything.  If I did anything wrong, or if there is anything I need to change, please let me know!

2022-03-16 16:57 UTC, BowserSlug commented
🚀 This PR matches 1 function (+0.01%) on `us`.

2022-03-16 17:42 UTC, nanaian requested changes
Awesome first decomp work! I've made some comments, feel free to contact us in the Discord if have any trouble

2022-03-16 17:42 UTC, nanaian commented on src/battle/move/shell_crack/77F240.c
> +/* Warning: struct ActorBlueprint is not defined (only forward-declared) */
Can remove these comments
```suggestion
```

2022-03-16 18:47 UTC, nanaian requested changes

2022-03-16 18:47 UTC, nanaian commented on src/battle/move/shell_crack/77F240.c
> +int func_802A10A4_77F2E4(void) {
This is almost certainly a script API function (judging from the `return 2`), so please make its signature the following
```suggestion
ApiStatus func_802A10A4_77F2E4(Evt* script, s32 isInitialCall) {
```

2022-03-16 18:47 UTC, nanaian commented on src/battle/move/shell_crack/77F240.c
> +    return 2;
```suggestion
    return ApiStatus_DONE2;
```

2022-03-16 19:41 UTC, nanaian requested changes
Style nits; LGTM otherwise

2022-03-16 19:41 UTC, nanaian commented on src/battle/move/shell_crack/77F240.c
> +    {
```suggestion
    for(i = 0; i < 20; i++) {
```

2022-03-16 19:41 UTC, nanaian commented on src/battle/move/shell_crack/77F240.c
> +    }
```suggestion
    }

```

2022-03-16 19:46 UTC, Nasina7 commented
Accidentally reverted those changes while fixing the fx_floating_cloud_puff issue.  Should be fixed now.

2022-03-16 19:48 UTC, nanaian requested changes
oop

2022-03-16 19:48 UTC, nanaian commented on src/battle/move/shell_crack/77F240.c
> +    for(i = 0; i < 20; i++) {
```suggestion
    for (i = 0; i < 20; i++) {
```

2022-03-16 20:11 UTC, Nasina7 commented
:+1:

2022-03-17 02:58 UTC, ethteck requested changes
Looks great! Just this small change and should be good to merge. and welcome :)

2022-03-17 02:58 UTC, ethteck commented on src/battle/move/shell_crack/77F240.c
> +    ActorState* playerActorState;
```suggestion
    ActorState* playerActorState = &gBattleStatus.playerActor->state;
```

2022-03-17 02:58 UTC, ethteck commented on src/battle/move/shell_crack/77F240.c
> +    playerActorState = &gBattleStatus.playerActor->state;
this line can be moved into the declaration (as shown above)

2022-03-17 03:05 UTC, merged