Finish lakilester overworld file
pmret/papermario pull request #669
Opened 2022-03-23 00:51 UTC by Rainchus

2022-03-23 00:53 UTC, BowserSlug commented
⚠️ This PR introduces 19 warnings:
- src/891b0_len_fb0.c:21: warning: redundant redeclaration of `func_800EFE2C' in same scope
- src/891b0_len_fb0.c:22: warning: redundant redeclaration of `func_800F0248' in same scope
- src/891b0_len_fb0.c:23: warning: redundant redeclaration of `func_800F0490' in same scope
- src/891b0_len_fb0.c:24: warning: redundant redeclaration of `func_800F0864' in same scope
- src/891b0_len_fb0.c:25: warning: redundant redeclaration of `func_800F09EC' in same scope
- src/891b0_len_fb0.c:26: warning: redundant redeclaration of `func_800F0B3C' in same scope
- src/891b0_len_fb0.c:27: warning: redundant redeclaration of `D_80109480' in same scope
- src/891b0_len_fb0.c:28: warning: redundant redeclaration of `D_8010CFF0' in same scope
- src/891b0_len_fb0.c:29: warning: redundant redeclaration of `D_8010CFF4' in same scope
- src/sprite.c:212: warning: comparison between pointer and integer
- src/sprite.c:246: warning: implicit declaration of function `spr_load_sprite'
- src/sprite.c:246: warning: initialization makes pointer from integer without a cast
- src/sprite.c:260: warning: implicit declaration of function `fold_init'
- src/sprite.c:290: warning: initialization from incompatible pointer type
- src/sprite.c:310: warning: implicit declaration of function `spr_update_player_raster_cache'
- src/sprite.c:362: warning: implicit declaration of function `func_802DE780'
- src/sprite.c:389: warning: assignment from incompatible pointer type

2022-03-23 02:00 UTC, pixel-stuck commented on src/world/partner/lakilester.c
> +    f32 xPosTemp, yPosTemp, zPosTemp, sp2C;
Maybe better for these to be just x, y, z?

2022-03-23 03:00 UTC, Rainchus commented on src/sprite.c
>      if (sprite == 0) {
doing that and removing the pointless if statement does match

2022-03-23 13:52 UTC, ethteck requested changes

2022-03-23 13:52 UTC, ethteck commented on src/77480.c
> -
These spaces in this file shouldn't be added

2022-03-23 13:52 UTC, ethteck commented on src/sprite.c
> +typedef struct unkStructSprite {
UnkStructSprite - also I think UnkSpriteStruct is better, cause the other way sounds like this is a sprite and not a struct

2022-03-23 13:52 UTC, ethteck commented on src/sprite.c
> +        return 1;
should still return TRUE and FALSE

2022-03-23 13:52 UTC, ethteck commented on src/world/partner/lakilester.c
> +void func_800EF3D4(s16);                               /* extern */
All the m2c comments should be removed

2022-03-23 13:52 UTC, ethteck commented on src/world/partner/lakilester.c
> +s32 player_raycast_up_corners(PlayerStatus*, f32*, f32*, f32*, f32*, f32); /* extern */
Any function declarations from other files like player_raycast_up_corners should go into functions.h and not here in this file

2022-03-23 13:52 UTC, ethteck commented on src/world/partner/lakilester.c
> +    Camera* cameras = &gCameras[CAM_DEFAULT];
this is "camera" rather than "cameras"

2022-03-23 13:52 UTC, ethteck commented on src/world/partner/lakilester.c
> +                npc->pos.x += ((npc->moveToPos.x - npc->pos.x) / npc->duration);
outer parens on this and the below two lines can be removed

2022-03-23 13:52 UTC, ethteck commented on src/world/partner/lakilester.c
> +            camYaw = cameras[0].currentYaw;
all occurrences of `cameras[0]` should instead be `camera->`

2022-03-25 08:42 UTC, ethteck requested changes
2 smols

2022-03-25 08:42 UTC, ethteck commented on src/world/partner/lakilester.c
> +#include "functions.h"
functions.h is part of common.h so this isn't necessary

2022-03-25 08:42 UTC, ethteck commented on src/world/area_arn/arn_08/events.c
> -void func_800EF3D4(s16);
this function decl shouldn't be necessary anymore, since it's in functions.h

2022-03-26 03:23 UTC, nanaian approved these changes

2022-03-26 10:36 UTC, ethteck approved these changes

2022-03-26 10:37 UTC, merged