Various dompin
pmret/papermario pull request #672
Opened 2022-03-29 11:33 UTC by ethteck

Finishes hammer.c and matches some various things including some previous non-matchings

2022-03-29 11:35 UTC, BowserSlug commented
🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀 This PR matches 13 functions (+0.23%) on `us`.

✅ This PR fixes 3 warnings!

2022-03-30 09:40 UTC, nanaian requested changes

2022-03-30 09:40 UTC, nanaian commented on src/167570.c
> +                                             (gWindows[gWindows[47].parent].height / 2) : 120) - gWindows[47].height / 2;
These ternaries are hard to read imo, I'd write them as something like
```suggestion
                        gWindows[47].pos.x = gWindows[47].parent != -1
                            ? gWindows[gWindows[47].parent].width / 2) - 91
                            : 69;
                        gWindows[47].pos.y = (
                            gWindows[47].parent != -1
                                ? (gWindows[gWindows[47].parent].height / 2)
                                : 120
                        ) - gWindows[47].height / 2;
```

2022-03-30 09:40 UTC, nanaian commented on src/167570.c
> +                                             (gWindows[gWindows[47].parent].height / 2) : 120) - gWindows[47].height / 2;
" ternaries

2022-03-30 09:40 UTC, nanaian commented on src/167570.c
> +                                             (gWindows[gWindows[47].parent].height / 2) : 120) - gWindows[47].height / 2;
"

2022-03-30 09:40 UTC, nanaian commented on src/167570.c
> +                                             (gWindows[gWindows[47].parent].height / 2) : 120) - gWindows[47].height / 2;
asdfg how does this appear like 4 times lol

2022-03-30 09:40 UTC, nanaian commented on src/world/action/hammer.c
> +    for (i = 1; i < 0x10; i++) {
```suggestion
    for (i = 1; i < 16; i++) {
```

2022-03-30 09:40 UTC, nanaian commented on src/world/action/hammer.c
> +        for (i = 1; i < 0x10; i++) {
```suggestion
        for (i = 1; i < 16; i++) {
```

2022-03-30 12:07 UTC, merged