rest of 5B320
pmret/papermario pull request #713
Opened 2022-05-18 20:45 UTC by HailSanta

2022-05-18 20:47 UTC, BowserSlug commented
⚠️ This PR introduces 10 warnings:
- src/5B320.c:1553: warning: initialization from incompatible pointer type
- src/5B320.c:1553: warning: initialization from incompatible pointer type
- src/5B320.c:1553: warning: initialization from incompatible pointer type
- src/5B320.c:1553: warning: initialization from incompatible pointer type
- src/5B320.c:1553: warning: initialization from incompatible pointer type
- src/5B320.c:1553: warning: initialization makes integer from pointer without a cast
- src/5B320.c:1553: warning: initialization makes integer from pointer without a cast
- src/5B320.c:1553: warning: initialization makes integer from pointer without a cast
- src/5B320.c:1553: warning: initialization makes integer from pointer without a cast
- src/5B320.c:1553: warning: initialization makes integer from pointer without a cast

2022-05-19 05:21 UTC, ethteck requested changes
Grood! Please replace tabs with 4 spaces though, and also the include files should be .inc.c instead of .c imo

2022-05-19 05:21 UTC, ethteck commented on src/item_entity_scripts.c
> +	ICON_anim_fp_0_palette,
spaces instead of tabs

2022-05-20 11:31 UTC, nanaian requested changes

2022-05-20 11:31 UTC, nanaian commented on src/C50A0.c
> +    for(i = 0; i < MAX_ITEM_ENTITIES; i++) {
```suggestion
    for (i = 0; i < MAX_ITEM_ENTITIES; i++) {
```

2022-05-20 11:31 UTC, nanaian commented on src/C50A0.c
> +    gCurrentItemEntities[id] = item = heap_malloc(sizeof(ItemEntity));
```suggestion
    gCurrentItemEntities[id] = item = heap_malloc(sizeof(*item));
```

2022-05-20 11:31 UTC, nanaian commented on src/item_entity_scripts.inc.c
> +ItemScript ItemScript_Jump = {
This should probably include the itemscript header

2022-05-21 04:46 UTC, nanaian approved these changes

2022-05-21 04:56 UTC, merged