various removal of hardcoded pointers
pmret/papermario pull request #721
Opened 2022-05-31 17:06 UTC by Rainchus

2022-05-31 17:08 UTC, BowserSlug commented
⚠️ This PR introduces 37 warnings:
- src/5B320.c:167: warning: initialization makes integer from pointer without a cast
- src/5B320.c:236: warning: initialization makes integer from pointer without a cast
- src/5B320.c:236: warning: initialization makes integer from pointer without a cast
- src/5B320.c:236: warning: initialization makes integer from pointer without a cast
- src/5B320.c:236: warning: initialization makes integer from pointer without a cast
- src/5B320.c:237: warning: initialization makes integer from pointer without a cast
- src/5B320.c:237: warning: initialization makes integer from pointer without a cast
- src/5B320.c:237: warning: initialization makes integer from pointer without a cast
- src/5B320.c:237: warning: initialization makes integer from pointer without a cast
- src/5B320.c:238: warning: initialization makes integer from pointer without a cast
- src/5B320.c:238: warning: initialization makes integer from pointer without a cast
- src/5B320.c:238: warning: initialization makes integer from pointer without a cast
- src/5B320.c:238: warning: initialization makes integer from pointer without a cast
- src/5B320.c:239: warning: initialization makes integer from pointer without a cast
- src/5B320.c:239: warning: initialization makes integer from pointer without a cast
- src/5B320.c:239: warning: initialization makes integer from pointer without a cast
- src/5B320.c:239: warning: initialization makes integer from pointer without a cast
- src/5B320.c:240: warning: initialization makes integer from pointer without a cast
- src/5B320.c:240: warning: initialization makes integer from pointer without a cast
- src/5B320.c:240: warning: initialization makes integer from pointer without a cast
- src/5B320.c:240: warning: initialization makes integer from pointer without a cast
- src/5B320.c:241: warning: initialization makes integer from pointer without a cast
- src/5B320.c:241: warning: initialization makes integer from pointer without a cast
- src/5B320.c:241: warning: initialization makes integer from pointer without a cast
- src/5B320.c:241: warning: initialization makes integer from pointer without a cast
- src/5B320.c:242: warning: initialization makes integer from pointer without a cast
- src/5B320.c:242: warning: initialization makes integer from pointer without a cast
- src/5B320.c:242: warning: initialization makes integer from pointer without a cast
- src/5B320.c:242: warning: initialization makes integer from pointer without a cast
- src/5B320.c:243: warning: initialization makes integer from pointer without a cast
- src/5B320.c:243: warning: initialization makes integer from pointer without a cast
- src/5B320.c:243: warning: initialization makes integer from pointer without a cast
- src/5B320.c:244: warning: initialization makes integer from pointer without a cast
- src/item_hud_script_table.inc.c:1: warning: type defaults to `int' in declaration of `HudScript_MoveDiamond'
- src/item_hud_script_table.inc.c:2: warning: type defaults to `int' in declaration of `HudScript_MoveDiamondDisabled'
- src/item_hud_script_table.inc.c:334: warning: initialization from incompatible pointer type
- src/item_hud_script_table.inc.c:334: warning: initialization from incompatible pointer type

2022-05-31 17:11 UTC, ethteck requested changes
nice! also gMessageBoxFrameParts isn't an array of ints, it's at least an array of int pointers. so I'd change its type to s32* [] instead of s32[]

2022-05-31 17:11 UTC, ethteck commented on src/item_hud_script_table.inc.c
> +extern HudScript_MoveDiamond[];
These need types

2022-05-31 17:11 UTC, ethteck commented on src/world/world.h
> +
extra newlines

2022-06-01 17:27 UTC, nanaian approved these changes

2022-06-02 02:56 UTC, merged