item entity functions and a few others
pmret/papermario pull request #725
Opened 2022-06-06 21:06 UTC by Unnunu

2022-06-06 21:08 UTC, BowserSlug commented
🚀🚀🚀🚀🚀🚀 This PR matches 6 functions (+0.16%) on `us`.

✅ This PR fixes 1 warnings!

2022-06-07 08:17 UTC, ethteck requested changes
🎊

2022-06-07 08:17 UTC, ethteck commented on src/C50A0.c
> +Lights1 D_8014C6C8 = gdSPDefLights1(255, 255, 255, 0, 0, 0, 0, 0, 0);
Oh nice. I've manually created some Light structs in some places because I didn't know about these. I'll have to go back and clean those up.

2022-06-07 08:17 UTC, ethteck commented on src/C50A0.c
> +            default:
Is this default case necessary? I think it should be able to be removed

2022-06-07 15:19 UTC, ethteck commented
ah, thanks for fixing those for me :)

2022-06-07 15:19 UTC, ethteck approved these changes

2022-06-08 23:36 UTC, nanaian approved these changes

2022-06-08 23:36 UTC, merged