match 2 mac_02 funcs, one needs data migration
pmret/papermario pull request #737
Opened 2022-06-26 12:48 UTC by Muskellunge

2022-06-26 13:02 UTC, BowserSlug commented
🚀 This PR matches 1 function (+0.00%) on `us`.

2022-06-26 13:04 UTC, ethteck requested changes

2022-06-26 13:04 UTC, ethteck commented on src/world/area_mac/mac_02/823BF0.c
> +extern s32 D_80248778_82BA38;
this extern can be removed since you have the one at the top of the file anyway

2022-06-26 13:13 UTC, ethteck approved these changes

2022-06-28 21:36 UTC, nanaian requested changes

2022-06-28 21:36 UTC, nanaian commented on src/world/area_mac/mac_02/823BF0.c
> +            D_8024E570[112] = 0;
```suggestion
            D_8024E570[i] = i + 16;
            D_8024E570[112] = 0;
```

2022-06-29 08:42 UTC, merged