match some functions in kmr_20/8EBE50.c
pmret/papermario pull request #742
Opened 2022-07-14 19:23 UTC by fewffwa

2022-07-14 19:25 UTC, BowserSlug commented
⚠️ This PR introduces 5 warnings:
- src/world/area_kmr/kmr_20/8EBE50.c:10: warning: return-type defaults to `int'
- src/world/area_kmr/kmr_20/8EBE50.c:11: warning: implicit declaration of function `func_8005566C'
- src/world/area_kmr/kmr_20/8EBE50.c:15: warning: return-type defaults to `int'
- src/world/area_kmr/kmr_20/8EBE50.c:30: warning: return-type defaults to `int'
- src/world/area_kmr/kmr_20/8EBE50.c:5: warning: return-type defaults to `int'

2022-07-15 12:52 UTC, nanaian requested changes

2022-07-15 12:52 UTC, nanaian commented on src/world/area_kmr/kmr_20/8EBE50.c
> +}
Please make this change to all 4 funcs
```suggestion
ApiStatus func_80240310_8EC130(Evt* script, s32 isInitialCall) {
    set_map_transition_effect(4);
    return ApiStatus_DONE2;
}
```

2022-07-15 12:53 UTC, nanaian commented on src/world/area_kmr/kmr_20/8EBE50.c
> +    func_8005566C(0, 0x3E8, 0x3F);
Can you declare this function in functions.h? i.e. add `void func_8005566C(s32, s32, s32);` to it

2022-07-15 17:18 UTC, ethteck approved these changes
Feel free to merge after alex's changes are addressed. The 0x3E8 would probably be better as 1000 as well

2022-08-07 02:53 UTC, merged