audio odyssey
pmret/papermario pull request #744
Opened 2022-07-22 04:17 UTC by HailSanta

2022-07-24 16:49 UTC, BowserSlug commented
🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀 This PR matches 160 functions (+1.06%) on `us`.

✅ This PR fixes 71 warnings!

2022-07-24 17:06 UTC, ethteck requested changes
Minor snibblets. We'll need a more thorough audio review also, hopefully..

2022-07-24 17:06 UTC, ethteck commented on src/world/area_end/end_00/DF9510.c
> +ApiStatus func_80242AD4_DF94D4(Evt *script, s32 isInitialCall) {
It should be wrapped in nonmatching in this case rather than commented out

2022-08-06 03:47 UTC, ethteck approved these changes

2022-08-06 09:03 UTC, nanaian approved these changes

2022-08-06 12:14 UTC, merged