several actor funcs
pmret/papermario pull request #748
Opened 2022-08-15 04:06 UTC by HailSanta

2022-08-15 04:08 UTC, BowserSlug commented
🚀🚀🚀🚀🚀🚀🚀🚀 This PR matches 8 functions (+0.17%) on `us`.

2022-08-15 04:10 UTC, ethteck requested changes
gg

2022-08-15 04:10 UTC, ethteck commented on ver/us/splat.yaml
> -    - [0x40BB70, data]
for the sake of record keeping/whatever, we tend to leave these as `- [0x40BB70]`

2022-08-15 04:14 UTC, ethteck approved these changes

2022-08-16 14:09 UTC, nanaian requested changes

2022-08-16 14:09 UTC, nanaian commented on src/182B30.c
> +    playerYaw = player->yaw;
```suggestion
    f32 playerYaw = player->yaw;
    f32 dx, dy, dz;

```

2022-08-16 14:09 UTC, nanaian commented on src/182B30.c
> +    for (i = 0; i < 20; i++) {
```suggestion
    for (i = 0; i < ARRAY_COUNT(rbuf); i++) {
```

2022-08-16 14:09 UTC, nanaian commented on src/182B30.c
> +    for (i = 0; i < 20; i++) {
```suggestion
    for (i = 0; i < ARRAY_COUNT(rbuf); i++) {
```

2022-08-16 14:09 UTC, nanaian commented on src/182B30.c
> +            break;
Indent switch contents pls

2022-08-17 01:04 UTC, merged