small and large boys
pmret/papermario pull request #749
Opened 2022-08-15 04:13 UTC by ethteck

2022-08-15 04:16 UTC, BowserSlug commented
🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀 This PR matches 19 functions (+0.24%) on `us`.

⚠️ This PR introduces 3 warnings:
- src/165490.c:51: warning: implicit declaration of function `filemenu_draw_message'
- src/167570.c:50: warning: implicit declaration of function `filemenu_draw_message'
- src/168590.c:27: warning: implicit declaration of function `filemenu_draw_message'
- src/169BE0.c:142: warning: implicit declaration of function `filemenu_draw_message'
- src/169BE0.c:62: warning: implicit declaration of function `mainmenu_draw_rect'
- src/16F740.c:2832: warning: assignment makes pointer from integer without a cast
- src/16c8e0.c:694: warning: assignment from incompatible pointer type

2022-08-15 04:18 UTC, BowserSlug commented
🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀 This PR matches 19 functions (+0.24%) on `us`.

2022-08-16 14:23 UTC, nanaian requested changes

2022-08-16 14:23 UTC, nanaian commented on src/16F740.c
> +                                            case 4:
Should probably use the status enum here

2022-08-16 14:23 UTC, nanaian commented on src/16F740.c
> +//INCLUDE_ASM(s32, "16F740", btl_state_update_first_strike);
```suggestion
```

2022-08-16 14:23 UTC, nanaian commented on src/sprite.c
> +        while ((s32) *componentList != -1) {
Absurd that they didnt use null to terminate lol

2022-08-16 14:23 UTC, nanaian commented on src/world/area_mac/mac_01/805DD0.c
> +ApiStatus func_802463E0_806C60(Evt* script, s32 isInitialCall) {
Is this a dup of func_80244D68_8055E8

2022-08-17 01:06 UTC, ethteck commented on src/world/script_api/7E0E80.c
>  // the evt_get_variable's at the beginning that makes absolutely no sense.
I didn't match it sadly. Just played with it a bit / got it closer

2022-08-17 01:15 UTC, merged