Sjg misc decomp
pmret/papermario pull request #766
Opened 2022-09-09 16:44 UTC by stephenJohnGiardina

2022-09-09 16:47 UTC, BowserSlug commented
🚀🚀🚀 This PR matches 3 functions (+0.01%) on `us`.

2022-09-09 16:49 UTC, pixel-stuck commented on src/world/area_kzn/kzn_02/C5AA50.c
> +    get_model_center_and_size(evt_get_variable(script, *args++), &sp20, &sp24, &sp28, &sp2C, &sp30, &sp34);
Forgot to mention this, but check this function's prototype, if the args are named (e.g. something more descriptive than arg0, etc.) then you can name your vars the same here (e.g. sp20 and co would have the same names as the arguments)

2022-09-09 16:50 UTC, pixel-stuck commented on src/world/area_kpa/kpa_04/A4BF60.c
> +ApiStatus func_802400BC_A4C01C(Evt *script, s32 isInitialCall) {
Star on the left rather than the right

2022-09-09 17:14 UTC, pixel-stuck commented
Looks like you've got a merge conflict now, for some reason; you'll need to resolve that before we can merge this

2022-09-10 08:01 UTC, nanaian requested changes

2022-09-10 08:01 UTC, nanaian commented on src/world/area_kzn/kzn_02/C5AA50.c
> +        partner = get_npc_unsafe(-4);
```suggestion
        partner = get_npc_unsafe(NPC_PARTNER);
```

2022-09-10 08:01 UTC, nanaian commented on src/world/area_kzn/kzn_02/C5AA50.c
> +    if (gPlayerData.currentPartner != 0){
```suggestion
    if (gPlayerData.currentPartner != PARTNER_NONE) {
```

2022-09-10 15:14 UTC, merged