player anim + collider surface types
pmret/papermario pull request #769
Opened 2022-09-11 20:37 UTC by HailSanta

2022-09-12 12:09 UTC, nanaian submitted a review, later dismissed

2022-09-12 12:09 UTC, nanaian commented on include/enums.h
> +    COLLIDER_FLAGS_SURFACE_TYPE      = 0x000000FF,
Perhaps suffix this name with _MASK to be consistent with the other one

2022-09-12 12:09 UTC, nanaian commented on src/891b0_len_fb0.c
> +    D_80109480 = get_collider_flags((u16)gCollisionStatus.currentFloor) & 0xFF;
```suggestion
    D_80109480 = get_collider_flags((u16)gCollisionStatus.currentFloor) & COLLIDER_FLAGS_SURFACE_TYPE_MASK;
```

2022-09-13 03:43 UTC, BowserSlug commented
✅ This PR fixes 2 warnings!

2022-09-13 05:59 UTC, ethteck approved these changes

2022-09-13 05:59 UTC, ethteck approved these changes

2022-09-13 06:02 UTC, ethteck requested changes

2022-09-13 06:02 UTC, ethteck commented on src/world/action/land.c
> +static void action_update_peach_land(void) {
please don't make any functions static - they won't show up in the elf

2022-09-13 06:10 UTC, ethteck approved these changes

2022-09-13 06:26 UTC, merged