Matching effects
pmret/papermario pull request #771
Opened 2022-09-12 21:33 UTC by mrshigure

2022-09-12 21:34 UTC, mrshigure commented on src/effects/effect_3D.c
> +#if NON_MATCHING
Couldn't get this one right: https://decomp.me/scratch/NufxC

2022-09-12 21:36 UTC, BowserSlug commented
🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀 This PR matches 12 functions (+0.26%) on `us`.

2022-09-13 06:29 UTC, ethteck requested changes
Excellent shtuff

2022-09-13 06:29 UTC, ethteck commented on src/effects/drop_leaves.c
> +    gDPSetPrimColor(gMasterGfxPos++, 0, 0, 0x14, 0x64, 0x14, part->unk_24);
decimal colors pleez

2022-09-13 06:36 UTC, ethteck approved these changes

2022-09-13 09:19 UTC, ethteck commented
> Wondering if the `_appendGfx` funcs would be better off taking `EffectInstance*` rather than `void*`.. @ethteck?

We can do this later if it works out, but there's evidence they take void* due to needing a temp for a0 in many of these functions

2022-09-13 09:50 UTC, nanaian approved these changes

2022-09-13 09:52 UTC, merged