func_80240DA4_EA9884: Match
pmret/papermario pull request #779
Opened 2022-09-16 22:24 UTC by savaughn

[https://decomp.me/scratch/WXzlT](https://decomp.me/scratch/WXzlT)

with help from 
[ethteck](https://decomp.me/u/ethteck)

2022-09-16 22:26 UTC, Brotenko requested changes

2022-09-16 22:26 UTC, Brotenko commented on src/EA8AE0.c
> +    dead_evt_get_variable(NULL, -50000000);
This should match
```suggestion
    dead_evt_get_variable(NULL, MapVar(0));
```

2022-09-16 22:27 UTC, BowserSlug commented
🚀 This PR matches 1 function (+0.00%) on `us`.

2022-09-17 04:26 UTC, ethteck approved these changes

2022-09-17 10:29 UTC, Brotenko approved these changes
gorb jod

2022-09-17 20:02 UTC, merged