Partner Funcs + Splupdate
pmret/papermario pull request #820
Opened 2022-10-13 06:47 UTC by ethteck

2022-10-13 06:47 UTC, ethteck commented
85%, fruggers

2022-10-13 06:51 UTC, BowserSlug commented
🚀🚀🚀🚀🚀🚀 This PR matches 6 functions (+0.21%) on `us`.

2022-10-14 11:27 UTC, nanaian requested changes
please make that macro (or preferably inline func!) :pray: :shipit:

2022-10-14 11:27 UTC, nanaian commented on src/battle/partner/parakarry.c
> +            state->currentPos.z = partner->currentPos.z;
Does a struct copy work `state->currentPos = partner->currentPos`?

2022-10-14 11:27 UTC, nanaian commented on src/battle/partner/parakarry.c
> +                } while (0);
mysterious inlined func?

2022-10-14 11:27 UTC, nanaian commented on src/battle/partner/parakarry.c
> +                } while (0); // TODO macro?
yes pls / inline func

2022-10-14 11:27 UTC, nanaian commented on src/battle/partner/parakarry.c
> +            state->moveTime--;
Add fallthrough comment

2022-10-14 11:27 UTC, nanaian commented on src/battle/partner/sushie.c
> +                } while (0);
"

2022-10-14 11:27 UTC, nanaian commented on src/battle/partner/sushie.c
> +                } while (0); // TODO macro?
"

2022-10-14 22:21 UTC, merged