msg stuff
pmret/papermario pull request #847
Opened 2022-11-01 21:52 UTC by Unnunu

2022-11-01 21:55 UTC, BowserSlug commented
🚀🚀🚀🚀🚀🚀🚀🚀 This PR matches 8 functions (+0.35%) on `us`.

⚠️ This PR introduces a warning:
- src/msg_data.c:147: warning: initialization from incompatible pointer type

2022-11-02 00:31 UTC, nanaian requested changes

2022-11-02 00:31 UTC, nanaian commented on src/msg_data.c
> +   10, 0, 0, 0
```suggestion
    10, 0, 0, 0
```

2022-11-02 11:19 UTC, nanaian approved these changes

2022-11-02 12:30 UTC, merged