battle partners
pmret/papermario pull request #852
Opened 2022-11-04 21:17 UTC by Unnunu

2022-11-04 21:20 UTC, BowserSlug commented
🚀🚀🚀 This PR matches 3 functions (+0.19%) on `us`.

2022-11-05 00:22 UTC, HailSanta commented on src/common/CalculateRotationZ.inc.c
>  #include "common.h"
I think you should call this file CalculateArcsinDeg and rename the function CalculateRotationZ -> CalculateArcsinDeg accordingly.

2022-11-05 00:54 UTC, ethteck requested changes

2022-11-05 00:54 UTC, ethteck commented on ver/us/splat.yaml
> -    - [0x6F2290]
These markers that explicitly say where the c code ends are still useful imo, even if they're not totally necessary

2022-11-05 00:54 UTC, ethteck commented on ver/us/splat.yaml
> -    - [0x708B70, data]
so this one would just be `- [0x708B70]` and 70BD00 can go away

2022-11-05 07:06 UTC, merged