ItemChoice_SaveSelected
pmret/papermario pull request #854
Opened 2022-11-08 13:00 UTC by ethteck

And some cleanup

2022-11-08 13:07 UTC, BowserSlug commented
🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀 This PR matches 33 functions (+0.05%) on `us`.

⚠️ This PR introduces 4 warnings:
- src/world/dead/kzn_19/EA8AE0.c:316: warning: redundant redeclaration of `dead_kzn_19_ItemChoice_HasSelectedItem' in same scope
- src/world/dead/kzn_19/EA8AE0.c:317: warning: redundant redeclaration of `dead_kzn_19_ItemChoice_SelectedItemID' in same scope

2022-11-08 13:18 UTC, Brotenko approved these changes

2022-11-10 00:30 UTC, nanaian requested changes

2022-11-10 00:30 UTC, nanaian commented on src/world/area_hos/hos_06/A3A230.c
> +            {
```suggestion
                evt_get_variable(NULL, AreaFlag(116 + i)) == 0
            ) {
```

2022-11-10 02:00 UTC, merged