5 fold funcs
pmret/papermario pull request #856
Opened 2022-11-12 17:02 UTC by Unnunu

2022-11-12 17:05 UTC, ethteck requested changes
gg!

2022-11-12 17:05 UTC, ethteck commented on src/d0a70_len_4fe0.c
> +    s32 raster;
offset / size comments please

2022-11-12 17:06 UTC, BowserSlug commented
🚀🚀🚀🚀🚀 This PR matches 5 functions (+0.24%) on `us`.

2022-11-12 17:12 UTC, ethteck approved these changes

2022-11-14 10:31 UTC, nanaian approved these changes

2022-11-14 10:34 UTC, merged