Match whirlwind effect
pmret/papermario pull request #869
Opened 2022-11-23 20:39 UTC by pixel-stuck

2022-11-23 20:51 UTC, BowserSlug commented
🚀🚀🚀 This PR matches 3 functions (+0.10%) on `us`.

2022-11-24 09:12 UTC, ethteck requested changes
nish!

2022-11-24 09:12 UTC, ethteck commented on src/effects/whirlwind.c
> +    part->primR = 0xFF;
decimal for the colors pleez

2022-11-24 09:12 UTC, ethteck commented on src/effects/whirlwind.c
> +    for(i = 0; i < 8; i++) {
ARRAY_LENGTH(x)

2022-11-24 09:12 UTC, ethteck commented on src/effects/whirlwind.c
> +void whirlwind_appendGfx(void *effect) {
pointer on the left

2022-11-24 09:12 UTC, ethteck commented on src/effects/whirlwind.c
> +}
empty line at end of file plez

2022-11-24 14:52 UTC, nanaian approved these changes

2022-11-24 14:57 UTC, merged