Windy leaves and water splash effects
pmret/papermario pull request #870
Opened 2022-11-24 16:54 UTC by pixel-stuck

2022-11-24 16:59 UTC, BowserSlug commented
🚀🚀🚀🚀🚀🚀 This PR matches 6 functions (+0.17%) on `us`.

2022-11-24 17:02 UTC, ethteck requested changes

2022-11-24 17:02 UTC, ethteck commented on src/effects/water_splash.c
> +    part->unk_30 = 0xFF;
decimal for these

2022-11-24 17:02 UTC, ethteck commented on src/effects/water_splash.c
> +                part->unk_10.x = shim_rand_int(0xA) - 2;
decimal for these

2022-11-24 17:02 UTC, ethteck commented on src/effects/windy_leaves.c
> +    WindyLeavesFXData *part = effect->data.windyLeaves;
could you put this var at the top? also left pointer

2022-11-24 17:02 UTC, ethteck commented on src/effects/windy_leaves.c
> +        part->alpha += (0xFF - part->alpha) * 0.3;
255 -

2022-11-24 17:02 UTC, ethteck commented on src/effects/windy_leaves.c
> +                part->unk_1C += func_E0200044(0x32, temp_a1 + i * 20) - 0x19;
decimal plz

2022-11-24 17:02 UTC, ethteck commented on src/effects/windy_leaves.c
> +                part->unk_1C += func_E0200044(0x32, temp_a1 + i * 20) - 0x19;
here2

2022-11-24 17:02 UTC, ethteck commented on src/effects/windy_leaves.c
> +                    part->unk_30 *= 0.9603999999999999;
does 0.9604 work? if not, that snuckz

2022-11-24 17:02 UTC, ethteck commented on src/effects/windy_leaves.c
> +                part->unk_1C += func_E0200044(0x32,  temp_a1 + i * 20) - 0x19;
dec

2022-11-24 17:02 UTC, ethteck commented on src/effects/windy_leaves.c
> +        default:
no default necessary

2022-11-24 18:13 UTC, ethteck approved these changes

2022-11-25 15:44 UTC, nanaian requested changes
Good stuff, few syntax nits where we're missing a space after keywords, there are more than the ones I noted

2022-11-25 15:44 UTC, nanaian commented on src/effects/water_splash.c
> +    for(i = 1; i < effect->numParts; i++, part++) {
```suggestion
    for (i = 1; i < effect->numParts; i++, part++) {
```

2022-11-25 15:44 UTC, nanaian commented on src/effects/water_splash.c
> +    for(i = 1; i < ((EffectInstance*)effect)->numParts; i++, data++) {
"

2022-11-25 15:44 UTC, nanaian commented on src/effects/windy_leaves.c
> +        switch(type) {
"

2022-11-25 16:06 UTC, merged