water block effect matched
pmret/papermario pull request #883
Opened 2022-12-11 09:06 UTC by pixel-stuck

2022-12-11 09:10 UTC, BowserSlug commented
🚀🚀🚀 This PR matches 3 functions (+0.09%) on `us`.

2022-12-11 09:29 UTC, ethteck requested changes

2022-12-11 09:29 UTC, ethteck commented on src/effects/gfx/water_block.c
> +#include "effects/gfx/D_09000538_3B7128.gfx.inc.c"
new line after this

2022-12-11 09:29 UTC, ethteck commented on src/effects/water_block.c
> +
extra empty line here

2022-12-12 06:00 UTC, ethteck approved these changes

2022-12-12 06:08 UTC, HailSanta approved these changes

2022-12-12 06:13 UTC, merged