matched 2 functions
pmret/papermario pull request #914
Opened 2023-01-17 23:18 UTC by Unnunu

2023-01-17 23:59 UTC, nanaian requested changes
small nit; good work!

2023-01-17 23:59 UTC, nanaian commented on src/7bb60_len_41b0.c
> +        } else if (hitID == -1){
```suggestion
        } else if (hitID == -1) {
```

2023-01-18 00:00 UTC, nanaian commented
@ethteck looks like Jenkins died, perhaps a retry is in order

2023-01-18 01:56 UTC, BowserSlug commented
🚀🚀 This PR matches 2 functions (+0.06%) on `us`.

2023-01-18 01:59 UTC, ethteck approved these changes

2023-01-18 06:58 UTC, merged